### ISSUE TITLE
Undetected MIT license for a solver result

### ISSUE THREAD

**Issue by fridex** [thoth-station/license-solver#12]
**Describe the bug**
When trying to detect license from a solver result that looks like this:

```json
         "metadata": {
            "Author": "Microsoft Corporation",
            "Author-email": "azpysdkhelp@microsoft.com",
            "Classifier": [
              "Development Status :: 4 - Beta",
              "Programming Language :: Python",
              "Programming Language :: Python :: 2",
              "Programming Language :: Python :: 2.7",
              "Programming Language :: Python :: 3",
              "Programming Language :: Python :: 3.5",
              "Programming Language :: Python :: 3.6",
              "Programming Language :: Python :: 3.7",
              "Programming Language :: Python :: 3.8",
              "License :: OSI Approved :: MIT License"
            ],
            "Description-Content-Type": "text/markdown",
            "Home-page": "https://github.com/Azure/azure-sdk-for-python",
            "License": "MIT License",
            "Metadata-Version": "2.1",
            "Name": "azure-mgmt-databoxedge",
            "Platform": [
              "UNKNOWN"
            ],
            "Requires-Dist": [
              "msrest (>=0.5.0)",
              "azure-common (~=1.1)",
              "azure-mgmt-core (<2.0.0,>=1.2.0)",
              "azure-mgmt-nspkg ; python_version<'3.0'"
            ],
            "Summary": "Microsoft Azure MyService Management Client Library for Python",
            "Version": "1.0.0b1"
          },
          "requires": [
            "msrest (>=0.5.0)",
            "azure-common (~=1.1)",
            "azure-mgmt-core (<2.0.0,>=1.2.0)",
            "azure-mgmt-nspkg ; python_version<'3.0'"
          ],
          "version": "1.0.0b1"
        },
        "index_url": "https://pypi.org/simple",
        "package_name": "azure-mgmt-databoxedge",
        "package_version": "1.0.0b1",
        "package_version_requested": "1.0.0b1",
        "sha256": [
          "f8fc9e7aad5ed620f3b4128cce50164087311442078f0ac1cfe034aec4aa635d",
          "bf594c8342194ff39000eeb3292a65f3339951d0af6bcf735b872ad72d5526f7"
        ]
      }
```

I get the following result:

```json
{
    "azure-mgmt-databoxedge": {
        "1.0.0b1": {
            "license": [
                "MIT License",
                "MIT"
            ],
            "license_version": "UNDETECTED",
            "classifier": [
                [
                    "License :: OSI Approved :: MIT License",
                    "MIT License"
                ]
            ],
            "warning": false
        }
    }
}
```

Both, classifiers and license field state MIT license so I would expect MIT license being detected.

**To Reproduce**
1. Download solver result `solver-rhel-8-py36-210818180221-213b67503ffbe5d5` from ocp4-test environment
2. Run thoth-license-solver on the given file
3. See the result reported

**Expected behavior**

I would expect the MIT license to be detected.

**Comment by meile18** [comment]
Hi @fridex, license detection is correct. But MIT License does not have versions. License and classifier are detected correctly. They are saved like a list. 
1. full name
2. short identifier

If the license and classifier do not match, warning index will be True.

**Comment by fridex** [comment]
> But MIT License does not have versions. License and classifier are detected correctly. They are saved like a list.

Does it mean that MIT license requires always the version in the license field to be detected?

**Comment by meile18** [comment]
MIT does not have versions. So program can't detect specific licenses which do not have a version.

**Comment by fridex** [comment]
> MIT does not have versions. So program can't detect specific licenses which do not have a version.

Would it be possible to detect also licenses that do not have any version associated such as in this case? I'm wondering how hard would it be.

**Comment by meile18** [comment]
after the PTO I'll look into it and try to find solution :smile:

**Comment by meile18** [comment]
Hi @fridex, the issue can be closed. If the license does not have a version will be printed _LICENSE-WITHOUT-VERSION_.

Pull request related to this issue: #14

**Comment by fridex** [comment]
> Hi @fridex, the issue can be closed. If the license does not have a version will be printed _LICENSE-WITHOUT-VERSION_ in license_version.
> 
> Pull request related to this issue: #14

Awesome, thanks a lot for the work 👍🏻 

/close
