### ISSUE TITLE
Provide a way to detect license directly from PyPI's metadata

### ISSUE THREAD

**Issue by fridex** [thoth-station/license-solver#27]
**Is your feature request related to a problem? Please describe.**

As a user of Thoth's license solver, I would like to have the ability to detect licenses directly from PyPI, something like this could do the trick: 

```
curl https://pypi.org/pypi/requests/json | thoth-license-solver --pypi-json
```

Alternatively (maybe more user friendly), a user can specify package and version and the tool will download JSON metadata from PyPI:

```
thoth-license-solver --package-name requests --package-version 2.26.0
```

**Describe alternatives you've considered**

Run thoth-solver and pass results to thoth-license-solver, but that might be not that intuitive (requires knowledge of thoth-solver). Also community adoption might be better if the tool provides a way to easily extract the license by passing package name and version (can default to latest).

**Comment by meile18** [comment]
it sounds very good!

/assign @meile18

**Comment by meile18** [comment]
Hi, @fridex, I looked at JSON, which are available from PyPI. They do not offer version licenses but only some global ones for all (if I understand correctly). We can implement `--package-name` without package version. What do you think?

**Comment by fridex** [comment]
Hi @meile18,

not sure if I follow correctly. PyPI offers the following JSON endpoints:

* https://pypi.org/pypi/requests/json
* https://pypi.org/pypi/requests/2.26.0/json

The latter one lists metadata specifically for the given release (2.26.0). The first one shows information for the latest release.

**Comment by meile18** [comment]
I didn't know there was such possibility. Thank you for clarification. 😄
